add `build-patched-image` and `cron-e2e-test-with-non-fast-block`

diff --git a/.github/workflows/e2e-subtensor-tests.yaml b/.github/workflows/e2e-subtensor-tests.yaml
--- a/.github/workflows/e2e-subtensor-tests.yaml
+++ b/.github/workflows/e2e-subtensor-tests.yaml
@@ -127,3 +127,108 @@ jobs:
               sleep 5
             fi
           done
+
+# `build-patched-image` and `cron-e2e-test-with-non-fast-block` should run once per week
+  build-patched-image:
+#    if: github.event_name == 'schedule'
+    runs-on: ubuntu-latest
+
+    outputs:
+      image-tag: ${{ steps.set-tag.outputs.tag }}
+
+    steps:
+#      - name: Check if today is Saturday
+#        id: set-status
+#        run: |
+#          day=$(date -u +%u)
+#          echo "Today is weekday $day"
+#          if [ "$day" -ne 6 ]; then
+#            echo "image_built=false" >> $GITHUB_OUTPUT
+#          else
+#            echo "image_built=true" >> $GITHUB_OUTPUT
+
+      - name: Clone + Patch (set 5 blocks instead of 7 days)
+        run: |
+          git clone https://github.com/opentensor/subtensor.git
+          cd subtensor
+          git checkout devnet-ready
+          sed -i 's|7 \* 24 \* 60 \* 60 / 12 // 7 days|5 // Only 5 blocks for tests|' runtime/src/lib.rs
+
+      - name: Build Docker image
+        run: |
+          cd subtensor
+          docker build -t subtensor-patched-devnet .
+
+      - name: Save Docker image
+        run: docker save subtensor-patched-devnet -o subtensor-patched-localnet.tar
+
+      - name: Upload image as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: subtensor-patched-localnet
+          path: subtensor-patched-localnet.tar
+
+
+  cron-e2e-test-with-non-fast-block:
+#    if: github.event_name == 'schedule' && needs.build-patched-image.outputs.image_built == 'true'
+
+    needs: [find-tests, build-patched-image]
+
+    runs-on: ubuntu-latest
+    timeout-minutes: 300
+
+    strategy:
+      fail-fast: false  # Allow other matrix jobs to run even if this job fails
+      max-parallel: 32  # Set the maximum number of parallel jobs (same as we have cores in ubuntu-latest runner)
+      matrix:
+        os:
+          - ubuntu-latest
+        test-file: ${{ fromJson(needs.find-tests.outputs.test-files) }}
+        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+
+    steps:
+      - name: Check-out repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v4
+
+      - name: install dependencies
+        run: uv sync --extra dev --dev
+
+      - name: Download Cached Docker Image
+        uses: actions/download-artifact@v4
+        with:
+          name: subtensor-patched-localnet
+
+      - name: Load Docker image
+        run: docker load -i subtensor-patched-localnet.tar
+
+      - name: Run patched E2E tests
+        env:
+          LOCALNET_IMAGE_NAME: ${{ needs.build-patched-image.outputs.image_name }}
+          FAST_BLOCKS: "False"
+        run: |
+          set +e
+          for i in 1 2 3; do
+            echo "🔁 Attempt $i: Running tests"
+            uv run pytest ${{ matrix.test-file }} -s
+            status=$?
+            if [ $status -eq 0 ]; then
+              echo "✅ Tests passed on attempt $i"
+              break
+            else
+              echo "❌ Tests failed on attempt $i"
+              if [ $i -eq 3 ]; then
+                echo "Tests failed after 3 attempts"
+                exit 1
+              fi
+              echo "Retrying..."
+              sleep 5
+            fi
+          done
